import 'package:xml/xml.dart';

class SvgValidationResult {
  const SvgValidationResult({
    required this.isValid,
    this.reason,
    this.regionIds = const [],
  });

  final bool isValid;
  final String? reason;
  final List<String> regionIds;
}

/// Validates SVG generated by AfaanKoo's coloring system.
///
/// The coloring SVG is intentionally restricted to simple vector paths.
/// Embedded images, scripts, external resources, event handlers and other
/// executable content are rejected.
class SvgSafetyValidator {
  const SvgSafetyValidator();

  SvgValidationResult validate(
    String svg, {
    int maxBytes = 700000,
  }) {
    // ------------------------------------------------------------
    // Basic validation
    // ------------------------------------------------------------

    if (svg.trim().isEmpty) {
      return const SvgValidationResult(
        isValid: false,
        reason: 'SVG is empty',
      );
    }

    if (svg.length > maxBytes) {
      return const SvgValidationResult(
        isValid: false,
        reason: 'SVG is too large',
      );
    }

    // ------------------------------------------------------------
    // Unsafe SVG elements
    // ------------------------------------------------------------

    final unsafeElements = RegExp(
      r'<\s*(script|image|foreignObject|iframe|audio|video|style)\b',
      caseSensitive: false,
    );

    if (unsafeElements.hasMatch(svg)) {
      return const SvgValidationResult(
        isValid: false,
        reason: 'SVG contains unsafe elements',
      );
    }

    // ------------------------------------------------------------
    // Unsafe event-handler attributes
    //
    // Examples:
    // onclick=
    // onload=
    // onmouseover=
    // ------------------------------------------------------------

    final unsafeAttributes = RegExp(
      r'\bon[a-zA-Z]+\s*=',
      caseSensitive: false,
    );

    if (unsafeAttributes.hasMatch(svg)) {
      return const SvgValidationResult(
        isValid: false,
        reason: 'SVG contains unsafe event handlers',
      );
    }

    // ------------------------------------------------------------
    // Javascript
    // ------------------------------------------------------------

    final javascriptPattern = RegExp(
      r'javascript\s*:',
      caseSensitive: false,
    );

    if (javascriptPattern.hasMatch(svg)) {
      return const SvgValidationResult(
        isValid: false,
        reason: 'SVG contains javascript',
      );
    }

    // ------------------------------------------------------------
    // Parse XML
    // ------------------------------------------------------------

    late XmlDocument document;

    try {
      document = XmlDocument.parse(svg);
    } on XmlParserException {
      return const SvgValidationResult(
        isValid: false,
        reason: 'Invalid SVG XML',
      );
    } catch (error) {
      return SvgValidationResult(
        isValid: false,
        reason: 'SVG parsing failed: $error',
      );
    }

    // ------------------------------------------------------------
    // Validate root
    // ------------------------------------------------------------

    final root = document.rootElement;

    if (root.name.local != 'svg') {
      return const SvgValidationResult(
        isValid: false,
        reason: 'Root element is not svg',
      );
    }

    // ------------------------------------------------------------
    // Only allow path elements
    //
    // Our generated coloring SVG should contain:
    //
    // <svg>
    //   <path ... />
    //   <path ... />
    // </svg>
    //
    // No images, groups, filters, styles, scripts, etc.
    // ------------------------------------------------------------

    for (final element in root.children.whereType<XmlElement>()) {
      if (element.name.local != 'path') {
        return SvgValidationResult(
          isValid: false,
          reason: 'Unsupported SVG element: ${element.name.local}',
        );
      }
    }

    // ------------------------------------------------------------
    // Find coloring regions
    // ------------------------------------------------------------

    final paths = root.findAllElements('path').toList();

    if (paths.isEmpty) {
      return const SvgValidationResult(
        isValid: false,
        reason: 'SVG has no colourable paths',
      );
    }

    final regionIds = <String>{};

    for (final path in paths) {
      final id = path.getAttribute('id');
      final data = path.getAttribute('d');

      // ----------------------------------------------------------
      // ID
      // ----------------------------------------------------------

      if (id == null || id.trim().isEmpty) {
        return const SvgValidationResult(
          isValid: false,
          reason: 'A path has no stable id',
        );
      }

      // IDs generated by AfaanKoo should only contain safe characters.
      final safeId = RegExp(
        r'^[a-zA-Z0-9_-]+$',
      );

      if (!safeId.hasMatch(id)) {
        return SvgValidationResult(
          isValid: false,
          reason: 'Region $id contains unsafe characters',
        );
      }

      // ----------------------------------------------------------
      // Duplicate IDs
      // ----------------------------------------------------------

      if (!regionIds.add(id)) {
        return SvgValidationResult(
          isValid: false,
          reason: 'Duplicate region id: $id',
        );
      }

      // ----------------------------------------------------------
      // Geometry
      // ----------------------------------------------------------

      if (data == null || data.trim().isEmpty) {
        return SvgValidationResult(
          isValid: false,
          reason: 'Region $id has no geometry',
        );
      }

      // ----------------------------------------------------------
      // Paths must be closed.
      //
      // Our vectorizer generates paths ending in Z.
      // ----------------------------------------------------------

      if (!data.trimRight().toUpperCase().endsWith('Z')) {
        return SvgValidationResult(
          isValid: false,
          reason: 'Region $id is not closed',
        );
      }

      // ----------------------------------------------------------
      // Reject advanced path commands.
      //
      // AfaanKoo currently generates only:
      //
      // M = move
      // H = horizontal line
      // V = vertical line
      // Z = close
      //
      // This keeps the SVG predictable and safe.
      // ----------------------------------------------------------

      final unsupportedPathCommands = RegExp(
        r'[CScSqQtTaA]',
        caseSensitive: false,
      );

      if (unsupportedPathCommands.hasMatch(data)) {
        return SvgValidationResult(
          isValid: false,
          reason: 'Region $id contains unsupported path geometry',
        );
      }
    }

    // ------------------------------------------------------------
    // Success
    // ------------------------------------------------------------

    return SvgValidationResult(
      isValid: true,
      regionIds: regionIds.toList(growable: false),
    );
  }
}